### ISSUE TITLE
有关脚注

### ISSUE THREAD

**Issue by OsbertWang** [latexstudio/LaTeXFAQ-cn#20]
在现有版本里，脚注都不带标号。暂时不知道什么原因。

**Comment by latexstudio** [comment]
脚注定义，可以看看，之前似乎是带圈数字好像。

**Comment by jack9603301** [comment]
脚注样式 只要重定义thefootnote即可 不建议使用带圈数字（看起来好像还是有点怪怪的）还是用[]舒服的多

**Comment by Sunshine-Zhang** [comment]
默认脚注不需要新增宏包，直接使用\footnot{脚注内容}可。该方法可以实现自动编号；首行缩进。

当你不需要首行缩进时，增加footmisc宏包，并使用marginal去掉首行缩进。
