### ISSUE TITLE
TeX/LaTeX的安装文件

### ISSUE THREAD

**Issue by Sunshine-Zhang** [latexstudio/LaTeXFAQ-cn#23]
Tex/LaTeX使用到现在已经更新了很多版本，而且安装内容与有些只要点击setup.exe的文件不同，比较繁琐，能不能介绍一下对LaTex安装文件分类、方法，使初学者不至于糊涂，而且它的更新很快，假如我原来的可以用，能不能不更新，如果有高版本的tex文件，存在兼不兼容的问题？小白问题哈，请多指教！

**Comment by Sunshine-Zhang** [comment]
LaTeX是一个排版软件，texlive是它的windows版本. WinEdt是tex文档的编译工具。也就是说Windows用户要配合使用texlive和WinEdt。

**Comment by htharoldht** [comment]
@Sunshine-Zhang 安装方法在本FAQs中第三章有详细的解释，至于分类、方法什么的，在本FAQs的第二部分有详细的解释。此外，安装方法其实网上有很多，LaTeX5000人交流群（QQ群）的群文件里面有管理员写的面向纯小白的安装教程，可以参考。

其实，TeXLive并不是面向Windows做的，它最初是Linux下的，后来增加了支持，使其实现了跨平台。WinEdt只是编辑器，并不是编译工具，WIndows下你可以使用WinEdt、TeXWorks、TeXStudio之类的软件，Mac下可以使用TeXShop、TeXPad之类的软件，以上均为面向TeX的专用软件，如果不满意，你还可以使用Sublime Text、VSCode、Atom等自行搭建，这些在网上均有详细的教程，[群主的网站](https://www.latexstudio.net)上也有足够的资料。

**Comment by jack9603301** [comment]
TexLive开始是否从linux开始实现我不知道 但是现在Texlive一样是属于latex发行包中，较为受欢迎的跨平台发行包 所以 讨论texlive的开发历史没有意义 因为任何软件的开发 都不可能一开始做的面面俱到。实际上也有很多的开源软件，也是 从linux开始开发，后续才会提供官方的跨平台编译支持，即便编译架构是跨平台的，也不代表官方提供其移植版本，对于尚未由官方直接提供的跨平台编译发行包的应用程序，除非由用户手动启用移植编译，也只有等官方真正开始考虑提供跨平台编译版才能直接下载。在这之前，很多软件连官方都没有在其他平台编译过甚至部分软件的源码上从架构上就不能直接移植的。
