### ISSUE TITLE
宏包或指令的使用顺序怎么确定

### ISSUE THREAD

**Issue by Sunshine-Zhang** [latexstudio/LaTeXFAQ-cn#24]
有时候，不是我的指令写错了，而是宏包或指令的顺序搞错了，造成指令不按照要求来做，比如页眉页脚的居中操作\cfoot{***}，编译也没问题，但是就是没有正常显示，此时需要geometry包的设置在fancy包前面。除了广博群书之外，这个问题有更好的解决办法吗

**Comment by htharoldht** [comment]
@Sunshine-Zhang 只能够凭借经验来判断。
一般情况下是没问题的，在发现问题后，去阅读相关的宏包说明文档，基本上就能够定位到这个问题了。
