### ISSUE TITLE
对本项目的几点建议

### ISSUE THREAD

**Issue by sd44** [latexstudio/LaTeXFAQ-cn#51]
我想对本项目pull request，有几个不成熟想法。

1. 结构方面。
是不是加入目录，依章节编号，而不是现在这样从头到尾依次排列下来？这样方便查找整理。

2. 本FAQ是不是可以做成容量大，知识点多的大FAQ。

3. 细节方面，统一和健全编写本FAQ的标准。例如具体条目列出可进一步参考文档的格式。简单举例  \emph{texdoc geometry}

4. 显著的todo和todolist小节，如todonotes包在此基础上还可以选择inline注释还是边注。这样的话，如我这等基础水平的用户也敢于pull，并且可以便于整理、集中问题，pull提出解决方案。

tex exchange上某用户应用todonotes的一个例子如下
``
\usepackage{xargs}
\usepackage[dvipsnames]{xcolor}  % Coloured text etc.
\usepackage[colorinlistoftodos,prependcaption,textsize=small]{todonotes}
\newcommandx{\unsure}[2][1=]{\todo[linecolor=red,backgroundcolor=red!25,bordercolor=red,#1]{#2}}
\newcommandx{\change}[2][1=]{\todo[linecolor=blue,backgroundcolor=blue!25,bordercolor=blue,#1]{#2}}
\newcommandx{\info}[2][1=]{\todo[linecolor=OliveGreen,backgroundcolor=OliveGreen!25,bordercolor=OliveGreen,#1]{#2}}
\newcommandx{\improve}[2][1=]{\todo[linecolor=Plum,backgroundcolor=Plum!25,bordercolor=Plum,#1]{#2}}
\newcommandx{\thiswillnotshow}[2][1=]{\todo[disable,#1]{#2}}``

**Comment by hushidong** [comment]
这是好提议呀，版主把它放这就是让大家来参与的。我之前就说过，大家不用犹豫，行动就对了。一人智短多人智长，latex 领域知识有点泛，一个人很难把那么多的宏包，知识都掌握，但每个人也都有自己的经验和心得，如果把自己擅长的添加进来，分享出来，这个faq可以越来越完善，越来越好的。我之前看你对字体设置那块很有研究，完全可以分享出来，当然还有其他更多你掌握的。

**Comment by jack9603301** [comment]
同意
