### ISSUE TITLE
编译中的字体问题

### ISSUE THREAD

**Issue by ddpom** [latexstudio/LaTeXFAQ-cn#60]
使用的系统为 Ubuntu 18.04 + texlive 2019（完全安装）, 已安装思源字体。（在运行命令 fc-list :lang=zh-cn >> zh.txt 后，可以看到 fonts-noto-cjk 已经安装）

但是推荐方式 `latexmk  -xelatex -synctex=1 -interaction=nonstopmode -shell-escape latex-faq-cn
` 编译后，不能产生 pdf. 信息如下：

> === TeX engine is 'XeTeX'
Latexmk: Log file says output to 'latex-faq-cn.xdv'
Latexmk: Summary of warnings from last run of (pdf)latex:
  =====Latex reported missing or unavailable character(s).
=====See log file for details.
Latexmk: Errors, so I did not complete making targets
Collected error summary (may duplicate other messages):
  xelatex: Command for 'xelatex' gave return code 1
      Refer to 'latex-faq-cn.log' for details
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs, or warnings treated as errors.

**Comment by stone-zeng** [comment]
请提供报错信息，或者 log 文件。仅凭 latexmk 的信息并不能判断问题。

**Comment by ddpom** [comment]
谢谢回复。
[latex-faq-cn.log](https://github.com/latexstudio/LaTeXFAQ-cn/files/4003986/latex-faq-cn.log)

**Comment by stone-zeng** [comment]
还是思源字体的问题……

命令行跑一下 `fc-list | grep 'Noto Serif CJK SC'` 看结果。能改的话，去 `latex-faq-cnc-class.cls` 里面删掉相关判断语句，直接

```tex
\setCJKmainfont{<你找到的字体>}  % Noto Serif CJK SC
\setCJKsansfont{<你找到的字体>}  % Noto Serif CJK SC
\setCJKmonofont{<你找到的字体>}  % Noto Sans CJK SC
```

不会改的话，按如下操作：

https://github.com/latexstudio/LaTeXFAQ-cn/blob/04b86b5b30f54c05e270e7baffc5b2b1a743ceb7/source/latex-faq-cn.tex#L8-L10

这个 repo 里面鱼龙混杂，暂时也没有太大动力持续维护，加之思源字体着实过于复杂，就先这样吧。

**Comment by ddpom** [comment]
多谢你的耐心！我看 `latex-faq-cnc-class.cls` 文件里面的设置太复杂了，就偷懒选择不使用自定义字体了。

更新：安装了百度网盘链接中的字体后，可以成功编译了。
