### ISSUE TITLE
关于 cls 的建议

### ISSUE THREAD

**Issue by zepinglee** [latexstudio/LaTeXFAQ-cn#9]
1. 建议先使用 `ctex` 的默认字体，思源字体在最后发布的时候再用。这样可以让作者专注于内容，而不必配置半天字体。

2. 建议增加规定，去掉行尾的空白符号。

3. `\begin{faq}` 改为命令式。因为它让大段的文字缩进起来，不如 `\subsection` 这样的命令方便。
另外代码中相邻两个问题之间空 2 行，方便代码阅读；排版的相邻问题之间多一些 vertical 空白。 

4. 行内的代码格式建议使用 `\cs`, `\marg` 这些宏，或者 `\verb`，如果能直接使用 `|code|` 就更好了。目前使用的是 `\mintinline{latex}{\MACRO}`，效果是绿色的，比较丑。

5. List 的间距需要缩小。

6. 需要配置 mono font，而且 sans font 和 mono font 应该 `Scale = MatchLowerCase`。

**Comment by stone-zeng** [comment]
1. 我加一个使用思源字体的开关吧，默认不开启。

2. 已经加了，暂时还没有推送过来。

3. `faq` 使用环境的原因是有可能会在结束位置加入别的代码，虽然目前还只是用 `\par` 占位。如果不需要做得很 fancy 实际上改用声明式的命令也可以，只是不知道群主是什么意见。

4. 我主张文本内的代码不需要做高亮，只有代码块才有这个必要。另外用 `minted` 会有额外的麻烦（需要 python），自定义也不太方便。之前在 `fduthesis` 里面尝试过的 `listing` 方案我可以移植过来，另外代码块希望分不同的语言来做，应该也会定义一些新的环境。唯一的不爽是写代码的时候编辑器没有良好的高亮（你用 vim 的话应该可以自己调……）。

5、6 不是很着急，我之后来改。

**Comment by stone-zeng** [comment]
@zepinglee 话说 mac 上面，无论在系统还是 texmf 树，字体通过文件名总能调用吧？

**Comment by zepinglee** [comment]
mac 系统的字体不能用文件名调用，texmf 的是可以的

**Comment by jack9603301** [comment]
关于faq环境的问题 可以定义成自动把标题设置\subsection的  然后建议定义一个子标题格式\subsubsection 作为回答中的子项目，这样依靠titleformat和titlecontent设置的标题 可以直接由toc系统生成目录

**Comment by stone-zeng** [comment]
@zepinglee 

> mac 系统的字体不能用文件名调用，texmf 的是可以的

但是在 <https://github.com/Stone-Zeng/fduthesis/issues/36>，你说的是

> 还有 xelatex 下 fontspec 只能按照文件名读取 texmf 的字体

所以是系统字体要**字体名**调用，TEXMF 的字体要**文件名**调用吗？

**Comment by stone-zeng** [comment]
刚才看了一下原来吴凌云前辈做的 FAQ，他那里是用一个 `\Question` 命令开始一个问题。要不我也换成这种命令的形式吧，你们推送过来之后我来改一下。

**Comment by zepinglee** [comment]
啊对没错，我刚做实验试了一下

**Comment by jack9603301** [comment]
今天的变更我已经推送

**Comment by stone-zeng** [comment]
做了如下修改：

- 问题改用 `\faq[选项]{问题}{id}` 这样的形式来写，后面跟 1 个空行；问题之间留 2 个空行。缩进也就不需要了。`id` 用小写英文字母加连字符的形式，必须保证唯一性。
- 行内的抄录用 `|...|` 的形式，行间暂且先用 `verbatim`，之后来改。
- 宏包、文档类分别使用 `\pkg{...}`、`\cls{...}` 标记。
- 字体的话，现在准备是这样的：
    - 正文字体：思源宋体 + Libertinus Serif
    - 无衬线字体：思源黑体 + Roboto
    - 等宽字体：思源黑体 + CM Unicode/Roboto Mono（前者用于行内抄录；后者用于代码块，暂时还没有调用）
    - 数学字体：Libertinus Math（已使用了 `unicode-math`）
    - 还会用到 Fetamont（`METAFONT`、`METAPOST` 的 logo）
- 如果字体遇到问题，可以加文档类选项 `use-customized-fonts=false` 关闭字体设置，即使用 LaTeX + CTeX 的默认配置（会与系统有关）

**Comment by jack9603301** [comment]
还没有在代码中改把？

**Comment by fragrans** [comment]
这个指引，要放入本FAQ的faq；我刚进来，根本无从下手。
